name: Build Antahpura Stage

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '21.7.1'
          cache: yarn

      - name: Install dependencies
        run: |
          yarn config set ignore-engines true
          yarn install --frozen-lockfile

      - name: Build stage
        run: yarn build

      - name: Package stage
        run: |
          cd dist
          zip -r ../antahpura-stage.zip .
          cd ..

      - name: Upload stage artifact
        uses: actions/upload-artifact@v4
        with:
          name: antahpura-stage
          path: antahpura-stage.zip
